-- Reuse the existing Supabase Storage bucket named "kamera".
-- This migration creates the per-camera photo metadata table only.

create table if not exists public.camera_photo (
  id bigint generated by default as identity primary key,
  camera_id bigint not null references public.camera(id) on delete cascade,
  image_url text not null,
  storage_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_camera_photo_camera_id_sort
  on public.camera_photo (camera_id, sort_order, id);

alter table public.camera_photo enable row level security;

create policy "Camera photos are readable by everyone"
  on public.camera_photo
  for select
  using (true);

create policy "Only admin users can manage camera photos"
  on public.camera_photo
  for all
  using (
    auth.uid() in (
      select user_id from public.admin_user where role = 'admin' and aktif = true
    )
  )
  with check (
    auth.uid() in (
      select user_id from public.admin_user where role = 'admin' and aktif = true
    )
  );
